name:                partial-isomorphisms
version:             0.2.3.0
github:              "schernichkin/partial-isomorphisms"
license:             BSD3
license-file:        LICENSE
author:              "Tillmann Rendel <rendel@informatik.uni-marburg.de>"
maintainer:          "Stanislav Chernichkin <schernichkin@gmail.com>"

extra-source-files:  
- README.md
- CHANGELOG.md

synopsis:            "Partial isomorphisms."
category:            Control
description:         "Partial isomorphisms as described in the
                     paper:
                     

                     Tillmann Rendel and Klaus Ostermann.
                     Invertible Syntax Descriptions:
                     Unifying Parsing and Pretty Printing.
                     In /Proc. of Haskell Symposium/, 2010.
                     
                     
                     The paper also describes invertible syntax
                     descriptions as a common interface for
                     parsers and pretty printers. These are
                     distributed separately in the
                     /invertible-syntax/ package."
homepage:            "http://www.informatik.uni-marburg.de/~rendel/unparse"


dependencies:
- base >= 4.15 && < 5
- template-haskell >= 2.17

library:
  source-dirs: src